version: "3.1"
services: 
  mongo0: 
    hostname: mongo0 
    container_name: mongo0 
    image: mongo:4.4.6
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: 123456 
    ports: 
    - 27017:27017
    restart: always 
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
  mongo1: 
    hostname: mongo1 
    container_name: mongo1 
    image: mongo:4.4.6
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports: 
     - 27018:27017 
    restart: always 
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
  mongo2: 
    hostname: mongo2 
    container_name: mongo2
    image: mongo:4.4.6 
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root 
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports: 
      - 27019:27017 
    restart: always 
    entrypoint: ["/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0"]
  mongo-express:
    container_name: mongo-client 
    image: mongo-express
    restart: always
    ports: 
      - 9090:8081 
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456 
      ME_CONFIG_MONGODB_SERVER: "mongo0,mongo1,mongo2"